prefetch_factor: 8

dataset_factory:
  type: hftext
  dataset: SimpleStories/SimpleStories
  text_column: story
  max_length: 512
  pack_to_max_length: false
  train_split: train
  validation_split: test

  tokenizer_factory:
    type: sentencepiece
    tokenizer_path: data/tokenizers/unigram_8K.model
