prefetch_factor: 8

dataset_factory:
  type: hftext_iterable
  dataset: BabyLM-community/BabyLM-2026-Strict
  text_column: text
  max_length: 512
  shuffle: true
  shuffle_buffer_size: 1024
  shuffle_seed: 42
  drop_last: true
  train_split: train
  validation_split: train
  interleave_holdout_every_n: 100

  tokenizer_factory:
    type: sentencepiece
    tokenizer_path: data/tokenizers/baby_unigram_4K.model
