model_parameters:
  type: transformer
  num_layers: 2
  embedding_dim: 256

  # Embedding layer factory configuration
  embedding_layer_factory:
    type: standardembeddinglayer
    vocab_size: 4000
    padding_idx: 3

  # Final normalization factory configuration
  final_norm_factory:
    type: rmsnorm

  # Transformer layer factory configuration
  transformer_layer_factory:
    type: standardtransformerlayer
    dropout: 0.0
    feedforward_dim: 1024

    activation_factory:
      type: gelu

    attention_norm_factory:
      type: rmsnorm

    feedforward_norm_factory:
      type: rmsnorm

    attention_factory:
      type: multiheadselfattention
      max_context: 512
      qk_dim: 64
      v_dim: 64
      causal: true
      n_heads: 4
      sdpa: true
      dropout: 0.0
      reproject: true

      positional_encoding_factory:
        type: rope
        base: 10000

