tokens_per_param: 175
training_time: 30
warmup_steps: 5

layer_sweep:
  type: layersweep
  descent_steps: 10
  lower_bound: 4
  method: first_above
  
learning_rate_sweep:
  type: learningratesweep
  sweep_time: 6 # 20% of total run time
  min_lr: 1.45E-3
  max_lr: 3.0E-2
  num_lrs: 5
  variance_window_size: 20
  variance_weight: 0.0 # Haven't ended up using this
