tokens_per_param: 20
training_time: 30
warmup_steps: 5

batch_size_finder:
  type: batchsizefinder
  descent_steps: 10

optuna_search:
  type: optunasearch
  n_trials: 30
  sweep_time: 6
  min_lr: 1.0E-4
  max_lr: 3.0E-2
  accumulated_batch_sizes: [128, 256, 512]
  min_num_layers: 4
  max_num_layers: 32
  vocab_sizes: [4, 8, 12]
  startup_trials: 5
